version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trello_clone
      TZ: 'America/Sao_Paulo'
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    external: true
